<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerWfAp6Qf\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerWfAp6Qf/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerWfAp6Qf.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerWfAp6Qf\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerWfAp6Qf\App_KernelDevDebugContainer([
    'container.build_hash' => 'WfAp6Qf',
    'container.build_id' => '4467721b',
    'container.build_time' => 1627588200,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerWfAp6Qf');
